// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Represents an investment fund that customers can invest in.
type Fund struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	CreatedAt string `json:"createdAt"`
}

// Represents a list of investment funds.
type FundList struct {
	// The list of funds available for investment.
	Funds []*Fund `json:"funds"`
}

// Represents an investment made by a customer.
type Investment struct {
	ID        string  `json:"id"`
	Fund      *Fund   `json:"fund"`
	Amount    float64 `json:"amount"`
	CreatedAt string  `json:"createdAt"`
}

// Input type for making an investment.
type InvestmentInput struct {
	// The ID of the customer making the investment.
	CustomerID string `json:"customerId"`
	// The ID of the fund the customer is investing in.
	FundID string `json:"fundId"`
	// The amount the customer wants to invest.
	Amount float64 `json:"amount"`
}

// A paginated list of investment records.
type InvestmentList struct {
	// The list of investments returned in this query.
	Investments []*Investment `json:"investments"`
	// The cursor to use for the next page of results.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
